#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCHEMA_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.scratch/wheel-of-time-search/schema.sql"

banner "Supabase setup: Wheel of Time semantic search"

# ── Stage 1: create the project ────────────────────────────────────────────
stage "Create the Supabase project"
say "This provisions the Postgres database (with pgvector) everything else"
say "in this wizard depends on."
open_url "https://supabase.com/dashboard/new"
step "Pick an organization, name the project (e.g. 'wheel-of-time-search'),"
step "set a database password (save it somewhere — you won't need it for"
step "this wizard, but you will if you ever connect via psql), pick a region,"
step "and click 'Create new project'."
step "Wait for provisioning to finish (~2 min) — the dashboard shows a"
step "spinner until the project is ready."
pause "Once the project dashboard is up, press Enter to continue."

# ── Stage 2: Supabase API credentials ──────────────────────────────────────
stage "Supabase API credentials"
say "SUPABASE_URL and SUPABASE_SERVICE_ROLE come from this project's API"
say "settings page."
step "In the project dashboard (already open from stage 1), click the gear"
step "icon → Project Settings → API."
step "Under 'Project URL', copy the URL."
ask SUPABASE_URL "Paste SUPABASE_URL:"
step "Under 'Project API keys', reveal and copy the 'service_role' key"
step "(NOT the anon/public key — this one bypasses row-level security, so"
step "the pipeline can write; keep it out of any client-side code)."
ask_secret SUPABASE_SERVICE_ROLE "Paste SUPABASE_SERVICE_ROLE:"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_SERVICE_ROLE "$SUPABASE_SERVICE_ROLE"

# ── Stage 3: OpenRouter API key ─────────────────────────────────────────────
stage "OpenRouter API key"
say "OPENROUTER_API_KEY is used later to embed chunks at both 768 and 3072"
say "dimensions via gemini-embedding-001, called through OpenRouter's"
say "OpenAI-compatible /embeddings endpoint rather than Google's Gemini API"
say "directly (see ADR-0003 — the direct GEMINI_API_KEY path stopped"
say "working, and OpenRouter's endpoint is confirmed to honor the"
say "'dimensions' parameter for this model)."
open_url "https://openrouter.ai/settings/keys"
step "Click 'Create API key' (or copy an existing one)."
ask_secret OPENROUTER_API_KEY "Paste OPENROUTER_API_KEY:"
write_env OPENROUTER_API_KEY "$OPENROUTER_API_KEY"

# ── Stage 4: run the schema migration ──────────────────────────────────────
stage "Run the schema migration"
say "This creates the vector extension, the documents table (content +"
say "both embedding columns + source_url per ADR-0001/ADR-0002), a"
say "public-read RLS policy, and the two match_documents_* RPCs."
say "The SQL lives at: $SCHEMA_FILE"
step "In the project dashboard, click the SQL Editor icon in the left"
step "sidebar → New query."
step "Open the file above, copy its full contents, paste into the SQL"
step "editor, and click 'Run'."
step "It should report success with no errors (every statement is"
step "idempotent, so re-running it later is safe)."
confirm "Did the migration run without errors?" || warn "Fix the error in the SQL editor before continuing, then re-run this script."

# ── Stage 5: manual smoke test ─────────────────────────────────────────────
stage "Smoke test: confirm both RPCs return results"
say "Run these as two SEPARATE statements in the SQL editor (not combined"
say "into one WITH query — a data-modifying CTE and the rest of its own"
say "statement share one snapshot, so a fresh 'select from documents' done"
say "by the RPC inside that same statement won't see the row it just"
say "inserted; splitting into two statements gives the second one a new"
say "snapshot that does see it)."
note ""
step "1. Insert the dummy row:"
cat <<'SQL'
  insert into documents (content, source_url, embedding_768, embedding_3072)
  values (
    'smoke test row',
    'https://wot.fandom.com/wiki/Test',
    array_fill(1, array[768])::vector,
    array_fill(1, array[3072])::vector
  );
SQL
note ""
step "2. Then, as a separate Run, call both RPCs against that row's own"
step "   embedding — each should return it first with similarity ~1:"
cat <<'SQL'
  select 'match_documents_768' as rpc, * from match_documents_768(
    (select embedding_768 from documents where content = 'smoke test row' limit 1), 5
  )
  union all
  select 'match_documents_3072' as rpc, * from match_documents_3072(
    (select embedding_3072 from documents where content = 'smoke test row' limit 1), 5
  );
SQL
note ""
step "Confirm you see one row back from each RPC with similarity ~1."
step "Then clean up the dummy row:"
cat <<'SQL'
  delete from documents where content = 'smoke test row';
SQL
confirm "Did both RPCs return a row, and did you delete the dummy row?" || warn "Re-check the RPCs before marking this ticket done."
# ──────────────────────────────────────────────────────────────────────────

finish
